### ISSUE TITLE
Wrong syntax when not all format are selected

### ISSUE THREAD

**Issue by moimael** [itgalaxy/webfont#3]
HI,

I'm using webfont to generate woff and woff2 icon fonts. The problem is that the generated css file has a syntax error, so webpack is unable to process it.

```css
@font-face {
    font-family: universalavenue;
    
    src:
        
        url("../../public/fonts/universalavenue.woff2") format("woff2"),
        url("../../public/fonts/universalavenue.woff") format("woff"),
        
        
    font-style: normal;
    font-weight: 400;
}
```

Apart from the extra empty lines (which do not cause issue but are not pretty), you can see that src do not end with a semicolon as it should.

Thanks !
